### ISSUE TITLE
Weka 3.8.3 .dmg file fails to mount

### ISSUE THREAD

**Issue by silverjim12** [Waikato/weka-3.8#1]
Hello,
I am trying to install Weka 3.8.3 to my macbook which is running on osX v10.11.6 El Capitan and the dmg file fails to mount (no mountable filesystems).

![screen shot](https://user-images.githubusercontent.com/29506210/47263673-c370ad00-d50e-11e8-97a5-7ed2b2c5cc4d.png)

Weka 3.6.15 gets installed without any problems though.
Could you please check?

Thank you

**Comment by eibe** [comment]
Have you tried downloading it again?

**Comment by silverjim12** [comment]
Yes I have.
I have also tried to mount it from the terminal using 
`hdiutil attach`
 but still no luck.

**Comment by eibe** [comment]
OK. I don't have a Mac at home, so I can't try it at the moment. As an
alternative, you can download the platform-independent .zip file. If Java
is installed on your device, you can just double-click on the weka.jar file
located in that .zip file to run Weka.

**Comment by silverjim12** [comment]
Maybe it's a backward compatibility issue.
Check this post
[https://forum.qt.io/topic/86672/qt-dmg-no-mountable-file-systems-on-el-capitan-backwards-compatibility-issue/4](url)

**Comment by silverjim12** [comment]
Yes the jar file works fine.
I am just raising this issue for you to check.

**Comment by silverjim12** [comment]
Hi,
Now it works! Thanks a lot!

Keep up the good work.
