### ISSUE TITLE
autoweka problem stable win 8 new java new python all 64 bit and plugin manager to get autoweka and a data set from autoweka german credit

### ISSUE THREAD

**Issue by josheeg** [Waikato/weka-3.8#12]
autoweka problem stable win 8 new java new python all 64 bit and plugin manager to get autoweka and a data set from autoweka german credit

17:18:02: java.lang.RuntimeException: Error marshalling XML response

could I be missing requirements?

**Comment by fracpete** [comment]
Use the Weka mailing list for questions and problems. See link in README.

**Comment by josheeg** [comment]
thats not a answer

**Comment by fracpete** [comment]
Weka and its mailing list have been around for a lot longer than github or even git. This mirror repo is just a courtesy. If you want answers to your problems/questions, then please use the correct channel, ie the Weka mailing list.
