### ISSUE TITLE
Weka Warning

### ISSUE THREAD

**Issue by MilanCugur** [Waikato/weka-3.8#19]
Hi,

When train to build and run my `Weka` model (from the Java API) without the `mtj` dependency, I get the folling error:

`WARNING: core mtj jar files are not available as resources to this classloader (sun.misc.Launcher$AppClassLoader@18b4aac2)`

My question is whether prior warning and non-inclusion of the mentioned library affects the correctness of code execution or only its performance? 
If it affects performance, how much?

Thanks in advance,
Milan

**Comment by fracpete** [comment]
Please use the [Weka mailing list](https://list.waikato.ac.nz/postorius/lists/wekalist.list.waikato.ac.nz/) for questions regarding Weka. These github repos are just readonly mirrors of the official subversion repository.

**Comment by MilanCugur** [comment]
Thank you for the response.
