### ISSUE TITLE
Search by text in filters frame

### ISSUE THREAD

**Issue by MacroBet** [Waikato/weka-3.8#41]
Dear developers,
I have been using Weka by GUI, i would suggest you to add a text search to the frame used to select filters.
<img width="370" alt="CleanShot 2021-10-12 at 10 12 23@2x" src="https://user-images.githubusercontent.com/16084750/136918254-8b591b86-10d0-4f7f-9f95-e17b45f5d3f1.png">

This could really improve the usability of the app.

Version 3.8.5

**Comment by fracpete** [comment]
If you'd like a feature like this, then try the Weka Investigator (a more powerful version of the Explorer) that is part of ADAMS:

https://adams.cms.waikato.ac.nz/
