### ISSUE TITLE
weka.filters.unsupervised.attribute.RandomSubset not using numAttribute variable

### ISSUE THREAD

**Issue by Grimbyy** [Waikato/weka-3.8#44]
When using RandomSubset I found that when trying to remove an amount of attributes (proportion %) it always defaults to 50% no matter the input.

![image](https://user-images.githubusercontent.com/56933645/163199628-4fc22097-cdf9-4bde-8553-159c0e943773.png)

Console output:
![image](https://user-images.githubusercontent.com/56933645/163199698-75436fa9-863f-4e1c-a16e-c742cf928902.png)

**Comment by fracpete** [comment]
You're initializing the filter wrong. The `setInputFormat` call has to happen **after** all options have been set. However, you're setting the percentage of attributes to use **after** the filter got initialized with the data (using a percentage of 0.5 at that stage).
