### ISSUE TITLE
"git clone weka" and "java run" in terminal?

### ISSUE THREAD

**Issue by giordano-cm** [Waikato/weka-3.8#8]
Can't i just "git clone weka" into some local repository of mine and run it in any terminal i open? It would be easier to use weka, because every update we would know and could simply make "git pull". Is somehow possible to do it?

**Comment by fracpete** [comment]
After any `git pull`, you will have to compile Weka first (the repo only contains the source code):
https://waikato.github.io/weka-wiki/compiling_weka/
For questions regarding Weka, please use the mailing list:
https://waikato.github.io/weka-wiki/mailing_list/
