### ISSUE TITLE
cannot select J48 in classify for latest weka

### ISSUE THREAD

**Issue by panfengzjz** [Waikato/weka-3.8#9]
Dear developer,
I am a new-comer for weka. And I have just installed weka 3.8.3 for windows 64bits.
After I installed it and opened a new file, I wanna classify it with decision tree (J48).
But I found the column is not able to click.
Could you give me some suggestion on how to deal with this issue?
![image](https://user-images.githubusercontent.com/21237635/63604572-bd4fcf00-c5fe-11e9-9bdb-e4196350ede3.png)

**Comment by fracpete** [comment]
Please use the Weka mailing list for questions regarding Weka. See Weka homepage for details.
